### PR TITLE
Declare runtime dependencies correctly in gemspec

### LINKED ISSUE #24: Declare runtime dependencies correctly
These 2 seem to be runtime dependencies, not just development dependencies
- `activesupport` - [required in code](https://github.com/brigade/db-query-matchers/blob/master/lib/db_query_matchers.rb#L5)
- `rspec` - [required in code](https://github.com/brigade/db-query-matchers/blob/master/lib/db_query_matchers/make_database_queries.rb#L1)

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fixes #24

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Build is green

**Comment by trotzig** [comment]
Great work, thanks for the quick turnaround! And thanks for taking this an extra step (adding appraisal to the mix).

**Comment by trotzig** [comment]
Released in 0.9.0

**Comment by PikachuEXE** [comment]
I use Appraisal in most of my gems
It's much easier for multi-version testing locally and generating different gemfiles
Thanks for releasing a new version quickly :)

**Pull request merged**
