### PR TITLE
Add support for custom query matchers in expectations

### PR DESCRIPTION
**Pull request by donaldpiret**
That can be either strings or regular expressions

### CODE REVIEW

**Comment by trotzig** [comment]
Hi @donaldpiret, and thanks for contributing to db-query-matchers! 

The code looks good. The interface is clear, special thanks for using "matching" as a verb, it makes the whole rspec expectation line read well. If I could ask you for one thing to add it would be to provide a little more detail in the commit messages. For me (and others at Brigade), the most important part of the commit message is to explain the why of the commit. I want to know more about why you decided to support both a string and a regexp as a matcher. I think you have a good reason, but without anything in the commit message about it, it's hard to evaluate. Here's a post that @lencioni wrote on the matter of commit messages: https://medium.com/brigade-engineering/the-secrets-to-great-commit-messages-106fc0a92a25

Again, thanks!

**Comment by donaldpiret** [comment]
Hey @trotzig, apologies for that. Thank you for the link to the article. It's a great read and I'll definitely try to improve my commit messages moving forward.

The reason for supporting both regular expressions and strings was that I wanted to be able to be both flexible in my matching (hence the regexp), and to quickly and easily match particular exact queries generated by for example an ActiveRecord scope.

This allows me for example to do: 
expect { request }.to_not make_database_queries(matching: User.deleted.to_sql).

Would you like me to fix the commit message and open another pull request?

**Comment by trotzig** [comment]
Thanks for providing that context, the string support makes more sense to me now.

I think (haven't tried this myself) you can just force-push to your branch after amending the commit messages. Then the PR will be automatically updated.

**Comment by trotzig** [comment]
I added some context myself to your commit messages, hope you don't mind. Merged as 5636a226fdc359afcfcc4581be3218f9c156558b and db4eb37494fade0ee14fd736a7e399e29240d1c0. Thanks for the contribution!

**Comment by donaldpiret** [comment]
Awesome, thank you and sorry I didn't manage to get to this earlier!

**Pull request closed without merging**
